In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

start_url = 'https://stocks.finance.yahoo.co.jp'
response = requests.get(start_url)
soup = BeautifulSoup(response.content, 'html.parser')

ind_urls1 = soup.find('ul', attrs={'class': 'blockFloat2Col'})
ind_urls2 = ind_urls1.find_all('li', attrs={'class': 'ymuiArrow1'})

df = pd.DataFrame()
ind_url_list = []
for i in ind_urls2:
    ind_url = i.find('a').get('href')
    ind_url_list.append(ind_url)
for ind_url in ind_url_list:

    get_inds_cwl_urls(ind_url_list[3])

df = df.reset_index(drop=True)

['https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0wMDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0xMDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0yMDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zMDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zMTAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zMTUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zMjAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zMjUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zMzAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zMzUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zNDAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zNDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zNTAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zNTUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zNjAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zNjUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zNzAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zNzUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz0zODAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz00MDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz01MDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz01MTAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz01MTUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz01MjAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz01MjUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz02MDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz02MTAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz03MDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz03MTAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz03MTUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz03MjAw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz04MDUw',
 'https://rdsig.yahoo.co.jp/finance/stocks/ids/20d/RV=1/RU=aHR0cHM6Ly9zdG9ja3MuZmluYW5jZS55YWhvby5jby5qcC9zdG9ja3MvcWkvP2lkcz05MDUw']

In [8]:
#各業種銘柄リストのURLを最後のページまで探索する
def get_inds_cwl_urls(url, count=1):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    table = soup.find('div', attrs={'id': 'listTable'})
    codes = table.find_all('td', attrs={'class': 'center yjM'})
    mkts = table.find_all('td', attrs={'class': 'center yjSt'})
    names = table.find_all('strong', attrs={'class': 'yjMt'})
    prices = table.find_all('div', attrs={'class': 'price yjM'})  
    get_init_values(url)
    
    count += 1
    search_next_url1 = soup.find('div', attrs={'class': 'yjListTab'})
    search_next_url2 = search_next_url1.find_all('a')
    for i in search_next_url2:
        if i.get_text() == str(count):
            next_url = start_url + i.get('href')
            print(next_url)
            time.sleep(1)
            get_inds_cwl_urls(next_url, count)

df = pd.DataFrame()
get_inds_cwl_urls(ind_url_list[3])
df = df.reset_index(drop=True)
df

https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=2
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=3
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=4
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=5
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=6
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=7

     code    市場             銘柄名    現在値
0    2001  東証1部            ニップン  1,605
1    2002  東証1部      日清製粉グループ本社  1,828
2    2003  東証1部          日東富士製粉  7,200
3    2004  東証1部            昭和産業  3,010
4    2009  東証1部            鳥越製粉    806
..    ...   ...             ...    ...
122  2931  東証1部           ユーグレナ    880
123  2932  東証2部  ＳＴＩフードホールディングス  4,510
124  2933  東証1部            紀文食品  1,645
125  4404  東証1部           ミヨシ油脂  1,236
126  4526  東証1部          理研ビタミン  1,427

[127 rows x 4 columns]

In [5]:
#業種1ページ分の初期特徴量（code、市場、銘柄名、現在値）を取得する
def get_init_values(url):
    df_temp = pd.DataFrame()
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    table = soup.find('div', attrs={'id': 'listTable'})
    codes = table.find_all('td', attrs={'class': 'center yjM'})
    mkts = table.find_all('td', attrs={'class': 'center yjSt'})
    names = table.find_all('strong', attrs={'class': 'yjMt'})
    prices = table.find_all('div', attrs={'class': 'price yjM'})
    
    #ズレを防止するため、各特徴量の数が同じか確認する（多分、ズレることはない）
    if len(codes) == len(mkts) == len(names) == len(prices):
        feature_values_dict = {'code':codes, '市場':mkts, '銘柄名':names, '現在値':prices}
        for key, values in feature_values_dict.items():
            codes_list = []
            for value in values:
                codes_list.append(value.get_text())
            df_temp[key] = codes_list
    else:
        print('数が違います')
    global df
    df_temp['銘柄名'] = df_temp['銘柄名'].str.replace('\(株\)', '')
    df = pd.concat([df, df_temp], axis=0)

df = pd.DataFrame()
get_init_values(ind_url_list[2])
df = df.reset_index(drop=True)
df

    code     市場              銘柄名    現在値
0   1400  東証JQG    ルーデン・ホールディングス    304
1   1401   マザーズ           エムビーエス    537
2   1407  東証JQS     ウエストホールディングス  3,035
3   1413   東証1部         ヒノキヤグループ  2,444
4   1414   東証1部   ショーボンドホールディングス  4,645
5   1417   東証1部    ミライト・ホールディングス  1,815
6   1418  東証JQS  インターライフホールディングス    214
7   1419   東証1部            タマホーム  2,353
8   1420   東証1部         サンヨーホームズ    758
9   1429   東証1部            日本アクア    525
10  1430   東証1部    ファーストコーポレーション    799
11  1431   マザーズ         Ｌｉｂ　Ｗｏｒｋ    814
12  1433   東証1部             ベステラ  1,509
13  1434   東証2部    ＪＥＳＣＯホールディングス    536
14  1435   東証1部       Ｒｏｂｏｔ　Ｈｏｍｅ    210
15  1436   マザーズ             フィット    920
16  1438   名証2部             岐阜造園  2,087
17  1439  東証JQS            安江工務店  1,023
18  1443   東証2部       技研ホールディングス    290
19  1444   名古屋セ             ニッソウ  2,389

In [9]:
df = pd.DataFrame()

get_inds_cwl_urls(ind_url_list[3])
df = df.reset_index(drop=True)
df

https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=2
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=3
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=4
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=5
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=6
https://stocks.finance.yahoo.co.jp/stocks/qi/?ids=3050&p=7

     code    市場             銘柄名    現在値
0    2001  東証1部            ニップン  1,605
1    2002  東証1部      日清製粉グループ本社  1,828
2    2003  東証1部          日東富士製粉  7,200
3    2004  東証1部            昭和産業  3,010
4    2009  東証1部            鳥越製粉    806
..    ...   ...             ...    ...
122  2931  東証1部           ユーグレナ    880
123  2932  東証2部  ＳＴＩフードホールディングス  4,510
124  2933  東証1部            紀文食品  1,644
125  4404  東証1部           ミヨシ油脂  1,236
126  4526  東証1部          理研ビタミン  1,427

[127 rows x 4 columns]

In [ ]:
import pandas as pd
columns = ['code', '銘柄名', '市場', '業種', '現在値', '出来高', '配当利回り',
           '予PER', '実PBR', '実POE', '売上（実）', '利益（実）', '売上/利益', '自己資本比率']
df = pd.DataFrame(columns=columns)
df

In [ ]:
codes_list = []
for code in codes:
    codes_list.append(code.get_text())
len(codes_list)

In [ ]:
import pandas as pd

df = pd.DataFrame()
df['code'] = codes_list
df

In [ ]:
feature_values_dict = {'code':codes, '市場':mkts, '銘柄名':names, '現在値':prices}
feature_values_dict.keys()

In [ ]:
import pandas as pd

df = pd.DataFrame()

ind_url_list[0]
response = requests.get(ind_url_list[0])
soup = BeautifulSoup(response.content, 'html.parser')

table = soup.find('div', attrs={'id': 'listTable'})
codes = table.find_all('td', attrs={'class': 'center yjM'})
mkts = table.find_all('td', attrs={'class': 'center yjSt'})
names = table.find_all('strong', attrs={'class': 'yjMt'})
prices = table.find_all('div', attrs={'class': 'price yjM'})

if len(codes) == len(mkts) == len(names) == len(prices):
    feature_values_dict = {'code':codes, '市場':mkts, '銘柄名':names, '現在値':prices}
    for key, values in feature_values_dict.items():
        codes_list = []
        for value in values:
            codes_list.append(value.get_text())
        df[key] = codes_list
else:
    print('数が違います')
df